# Generated by Django 4.0.4 on 2022-05-23 14:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('poster', models.ImageField(upload_to='images/anime-poster/', verbose_name='Постер')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('trailer', models.CharField(default='', max_length=500, verbose_name='Трайлер')),
            ],
            options={
                'verbose_name': 'Аниме',
                'verbose_name_plural': 'Аниме',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Жанры',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Звезда рейтинга',
                'verbose_name_plural': 'Звезда рейтинга',
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=0, verbose_name='Номер сезона')),
                ('year', models.PositiveSmallIntegerField(default=1990, verbose_name='Дата выхода сезона')),
                ('title', models.CharField(max_length=300, null=True, verbose_name='Название сезона')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime', verbose_name='fk_anime')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезон',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP адрес')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime', verbose_name='аниме')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.ratingstar', verbose_name='звезда')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинг',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True, verbose_name='Название фильма')),
                ('number', models.PositiveSmallIntegerField(default=0, verbose_name='Номер фильма')),
                ('image', models.ImageField(upload_to='images/episode-preview/')),
                ('file', models.FileField(upload_to='video/films/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime', verbose_name='fkf_anime')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильм',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True, verbose_name='Название серий')),
                ('number', models.PositiveSmallIntegerField(default=0, verbose_name='Номер серий')),
                ('image', models.ImageField(upload_to='images/episode-preview/')),
                ('file', models.FileField(upload_to='video/serials/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.season', verbose_name='fk_season')),
            ],
            options={
                'verbose_name': 'Серия',
                'verbose_name_plural': 'Серия',
            },
        ),
        migrations.CreateModel(
            name='AnimeShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='anime_shots/', verbose_name='Изображение')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime', verbose_name='Аниме')),
            ],
            options={
                'verbose_name': 'Кадры из аниме',
                'verbose_name_plural': 'Кадры из аниме',
            },
        ),
        migrations.AddField(
            model_name='anime',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anime.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(to='anime.genre', verbose_name='Жанры'),
        ),
    ]
