# Generated by Django 4.0.4 on 2022-05-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='year',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='category',
        ),
        migrations.AddField(
            model_name='anime',
            name='category',
            field=models.ManyToManyField(to='anime.category', verbose_name='Категория'),
        ),
    ]
