# Generated by Django 4.0.4 on 2022-05-13 10:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_remove_anime_year_remove_anime_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='poster',
            field=models.ImageField(upload_to='images/anime-poster/', verbose_name='Постер'),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=0, verbose_name='Номер сезона')),
                ('year', models.PositiveSmallIntegerField(default=1990, verbose_name='Дата выхода сезона')),
                ('title', models.CharField(max_length=300, verbose_name='Название сезона')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime', verbose_name='fk_anime')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезон',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название фильма')),
                ('number', models.PositiveSmallIntegerField(default=0, verbose_name='Номер фильма')),
                ('image', models.ImageField(upload_to='images/episode-preview/')),
                ('file', models.FileField(upload_to='video/films/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime', verbose_name='fkf_anime')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильм',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название серий')),
                ('number', models.PositiveSmallIntegerField(default=0, verbose_name='Номер серий')),
                ('image', models.ImageField(upload_to='images/episode-preview/')),
                ('file', models.FileField(upload_to='video/serials/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.season', verbose_name='fk_season')),
            ],
            options={
                'verbose_name': 'Серия',
                'verbose_name_plural': 'Серия',
            },
        ),
    ]
