# Generated by Django 4.0.4 on 2022-05-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_alter_anime_poster_season_film_episode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(max_length=150, null=True, verbose_name='Название серий'),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=150, null=True, verbose_name='Название фильма'),
        ),
        migrations.AlterField(
            model_name='season',
            name='title',
            field=models.CharField(max_length=300, null=True, verbose_name='Название сезона'),
        ),
    ]
